export const PROMISE = 'PROMISE';
export const USER_AUTHENTICATING = 'USER_AUTHENTICATING';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_AUTHENTICATION_FAILURE = 'USER_AUTHENTICATION_FAILURE';
